# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_text', models.CharField(max_length=200)),
                ('course_code', models.CharField(max_length=200)),
                ('course_desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_text', models.CharField(max_length=200)),
                ('userpassword', models.CharField(max_length=200)),
                ('recovery_question', models.CharField(max_length=200)),
                ('recovery_answer', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('course_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Course')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.PersonalDetails')),
            ],
        ),
    ]
